import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.APP_CONFIG||{}, msg=document.querySelector('#loginMsg');
if(!cfg.supabaseUrl||!cfg.supabaseAnonKey){msg.textContent='أكمل بيانات Supabase داخل config.js أولاً.';msg.className='form-message error';throw new Error('Missing config')}
const sb=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey), $=s=>document.querySelector(s);
async function authorize(){const {data:{session}}=await sb.auth.getSession();if(!session)return false;const {data}=await sb.from('profiles').select('role').eq('id',session.user.id).single();return data?.role==='admin'}
async function show(){if(!await authorize())return;$('#loginView').hidden=true;$('#adminView').hidden=false;const [{data:req},{data:courses}]=await Promise.all([sb.from('registration_requests').select('*,courses(title)').order('created_at',{ascending:false}),sb.from('courses').select('*')]);const r=req||[],c=courses||[];$('#mRequests').textContent=r.filter(x=>x.status==='جديد').length;$('#mAll').textContent=r.length;$('#mCourses').textContent=c.filter(x=>x.status==='متاح').length;$('#mFull').textContent=c.filter(x=>x.status==='مكتمل').length;$('#requestRows').innerHTML=r.map(x=>`<tr><td><b>${x.student_name}</b><br>${x.parent_name}</td><td><a href="https://wa.me/${x.phone.replace(/\D/g,'').replace(/^0/,'213')}" target="_blank">${x.phone}</a></td><td>${x.level}</td><td>${x.courses?.title||'—'}</td><td><select class="statusSelect" data-id="${x.id}"><option ${x.status==='جديد'?'selected':''}>جديد</option><option ${x.status==='تم التواصل'?'selected':''}>تم التواصل</option><option ${x.status==='مؤكد'?'selected':''}>مؤكد</option><option ${x.status==='مرفوض'?'selected':''}>مرفوض</option></select></td></tr>`).join('')||'<tr><td colspan="5">لا توجد طلبات بعد.</td></tr>';
$('#courseRows').innerHTML=c.map(x=>`<tr><td><b>${x.title}</b></td><td>${x.level}</td><td>${x.teacher_name}</td><td>${x.schedule}<br><small>${x.price} دج</small></td><td><select class="courseStatus" data-id="${x.id}"><option ${x.status==='متاح'?'selected':''}>متاح</option><option ${x.status==='مكتمل'?'selected':''}>مكتمل</option><option ${x.status==='مؤجل'?'selected':''}>مؤجل</option><option ${x.status==='منتهٍ'?'selected':''}>منتهٍ</option></select></td><td><button class="tiny archiveCourse" data-id="${x.id}">إخفاء</button></td></tr>`).join('')||'<tr><td colspan="6">لا توجد دروس بعد.</td></tr>';
document.querySelectorAll('.courseStatus').forEach(x=>x.onchange=async()=>{await sb.from('courses').update({status:x.value}).eq('id',x.dataset.id);show()});
document.querySelectorAll('.archiveCourse').forEach(x=>x.onclick=async()=>{if(confirm('هل تريد إخفاء هذا الدرس من الموقع؟')){await sb.from('courses').update({status:'منتهٍ'}).eq('id',x.dataset.id);show()}});document.querySelectorAll('.statusSelect').forEach(s=>s.onchange=async()=>{await sb.from('registration_requests').update({status:s.value}).eq('id',s.dataset.id)});}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const {error}=await sb.auth.signInWithPassword(d);if(error){msg.textContent='بيانات الدخول غير صحيحة.';msg.className='form-message error';return}if(!await authorize()){await sb.auth.signOut();msg.textContent='هذا الحساب لا يملك صلاحية الإدارة.';msg.className='form-message error';return}show()};
$('#courseForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.price=Number(d.price);d.seats_remaining=Number(d.seats_remaining);d.status='متاح';const {error}=await sb.from('courses').insert(d);const m=$('#courseMsg');m.textContent=error?'تعذر حفظ الدرس.':'تمت إضافة الدرس بنجاح.';m.className='form-message '+(error?'error':'success');if(!error){e.target.reset();show()}};$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};show();
