const fallback=[
{id:'demo-1',title:'الرياضيات',level:'متوسط',teacher_name:'الأستاذة سمية',schedule:'السبت والثلاثاء · 15:00',price:2500,seats_remaining:6,status:'متاح'},
{id:'demo-2',title:'اللغة الفرنسية',level:'لغات',teacher_name:'الأستاذ أمين',schedule:'الأحد والخميس · 16:30',price:2200,seats_remaining:4,status:'متاح'},
{id:'demo-3',title:'العلوم الطبيعية',level:'ثانوي',teacher_name:'الأستاذة نوال',schedule:'الإثنين والأربعاء · 17:00',price:3000,seats_remaining:0,status:'مكتمل'},
{id:'demo-4',title:'اللغة الإنجليزية',level:'لغات',teacher_name:'الأستاذة مريم',schedule:'السبت · 10:00',price:2000,seats_remaining:8,status:'متاح'},
{id:'demo-5',title:'اللغة العربية',level:'ابتدائي',teacher_name:'الأستاذ خالد',schedule:'الأحد والثلاثاء · 09:00',price:1800,seats_remaining:5,status:'متاح'},
{id:'demo-6',title:'الفيزياء',level:'ثانوي',teacher_name:'الأستاذ يوسف',schedule:'الجمعة · 14:00',price:3000,seats_remaining:3,status:'متاح'},
{id:'demo-7',title:'تحسين المستوى في اللغة الفرنسية',level:'تحسين المستوى - اللغات',teacher_name:'الأستاذة مريم',schedule:'الأربعاء والسبت · 16:00',price:2200,seats_remaining:7,status:'متاح'},
{id:'demo-8',title:'تعليم القرآن الكريم',level:'القرآن الكريم',teacher_name:'الأستاذ عبد الرحمن',schedule:'الجمعة · 09:30',price:1500,seats_remaining:10,status:'متاح'}];
let courses=fallback, active='all';
const $=s=>document.querySelector(s);
function format(n){return new Intl.NumberFormat('ar-DZ').format(n)+' دج'}
function render(){const list=active==='all'?courses:courses.filter(c=>c.level===active);$('#courseGrid').innerHTML=list.length?list.map(c=>`<article class="course-card"><div class="course-top"><span class="level">${c.level}</span><span class="status ${c.status!=='متاح'?'full':''}">${c.status==='متاح'?'متاح للتسجيل':c.status}</span></div><h3>${c.title}</h3><p class="teacher">${c.teacher_name||'أستاذ متخصص'}</p><div class="course-meta"><div><span>الموعد</span><br>${c.schedule||'يحدد لاحقاً'}</div><div><span>المقاعد</span><br>${c.seats_remaining??0} متبقية</div></div><div class="course-price">${format(c.price||0)} / شهر</div></article>`).join(''):'<p class="loading">لا توجد دروس في هذا القسم حالياً.</p>';}
function fillSelect(level=''){const s=$('#courseSelect');const valid=courses.filter(c=>c.status==='متاح'&&(!level||c.level===level));s.disabled=!level;s.innerHTML='<option value="">'+(level?'اختر الدرس':'اختر المستوى أولاً')+'</option>'+valid.map(c=>`<option value="${c.id}">${c.title} — ${c.teacher_name||''}</option>`).join('')}
async function load(){const cfg=window.APP_CONFIG||{};if(!cfg.supabaseUrl||!cfg.supabaseAnonKey){render();fillSelect();return}try{const r=await fetch(`${cfg.supabaseUrl}/rest/v1/courses?status=eq.%D9%85%D8%AA%D8%A7%D8%AD&select=*&order=created_at.desc`,{headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`}});if(!r.ok)throw Error();const data=await r.json();if(data.length)courses=data;render();fillSelect()}catch(e){render();fillSelect()}}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');active=b.dataset.filter;render()});
$('#registrationForm')?.querySelector('[name="level"]')?.addEventListener('change',e=>fillSelect(e.target.value));
$('#registrationForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=$('#formMessage'),button=e.submitter;msg.textContent='جاري إرسال طلبك…';msg.className='form-message';button.disabled=true;const data=Object.fromEntries(new FormData(e.target));try{const r=await fetch('/.netlify/functions/submit-registration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw Error(out.error);msg.textContent='تم إرسال طلبك بنجاح. سنتواصل معك قريباً.';msg.className='form-message success';e.target.reset()}catch(err){msg.textContent=err.message||'تعذر إرسال الطلب. يرجى المحاولة لاحقاً أو التواصل عبر واتساب.';msg.className='form-message error'}finally{button.disabled=false}});
window.addEventListener('scroll',()=>{$('#progressLine').style.width=(scrollY/(document.body.scrollHeight-innerHeight)*100)+'%'});document.querySelectorAll('[data-count]').forEach(el=>{let end=+el.dataset.count;let i=0;let x=setInterval(()=>{i+=Math.ceil(end/35);el.textContent=Math.min(i,end);if(i>=end)clearInterval(x)},35)});if($('#year')) $('#year').textContent=new Date().getFullYear();load();
